spring:
  profiles:
    active: test
  redis:
    database: 0
    jedis:
      pool:
        max-idle: 8 # 连接池中的最小空闲连接
        min-idle: 0 # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1m # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 连接超时时间（毫秒）
    timeout: 60000m
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: route_service_one
        uri: lb://auth-server
        predicates:
        - Path=/auth/server/**
        filters:
        - StripPrefix=2
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - id: route_service_two
        uri: lb://base-server
        predicates:
        - Path=/base/server/**
        filters:
        - StripPrefix=2
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true
  client:
    config:
      remote-service:
        connectTimeout: 1000
        readTimeout: 12000
eureka:
    instance:
      prefer-ip-address: true