server:
  port: 8765
spring:
  datasource:
    url: jdbc:mysql://192.168.2.68:3306/sxlc_auth?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: sxlc123456
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.2.68
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8763/auth/server/user
      prefer-token-info: false
      id: auth-server
#    client:
#      access-token-uri: http://127.0.0.1:8763/auth/server/oauth/token
#      user-authorization-uri: http://127.0.0.1:8763/auth/server/oauth/authorize